server.port=8081
spring.application.name=JSON Editor Demo

# Logging
logging.level.com.example.jsoneditor=INFO
logging.level.org.springframework.web=INFO

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Static resources
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/